name: Deploy to Shuttle

on:
  push:
    branches:
      - master # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_TOKEN }}
          project-id: proj_01K5C6C55RCF9TTCBA4BN8Y7NB
          secrets: | 
            GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 = '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}'
            GOOGLE_PROJECT_ID = '${{ secrets.GOOGLE_PROJECT_ID }}'
            FRONT_END_ENDPOINT = '${{ secrets.FRONT_END_ENDPOINT  }}'
            

